### PR TITLE
Enabling node port for cors-proxy

### PR DESCRIPTION
**Pull request by maneta**
Enablind NodePort for tcp ELB

### CODE REVIEW

**Review by mikz — COMMENTED** [review]
Why we need TCP ELB ?

**Comment by maneta** [comment]
@mikz Because **AFAIK** the Cors Proxy will receive requests with multiple `Host` right? And, as you know,  Openshift Routes binds only one `Host` per Route.

Am I missing something?

**Comment by mikz** [comment]
@maneta yes. Cors-proxy is either directly exposed on one domain or proxied from another domain (that can change the host to be correct). It does not use the Host header to proxy anything, so that can be used by openshift to determine the host.

**Comment by maneta** [comment]
All Right @mikz I got it now. Thanks!

**Pull request closed without merging**
